CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PACKAGE_ID NUMBER,
    CURRENT_INVENTORY_COUNT NUMBER(5),
    STORE_COST NUMBER(10, 2),
    SALE_PRICE NUMBER(10, 2),
    LAST_UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30),
    PET_FLAG VARCHAR2(1),
    CONSTRAINT fk_product_package
        FOREIGN KEY (PACKAGE_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE CUSTOMER (
    CUST_ID NUMBER PRIMARY KEY,
    FIRSTNAME VARCHAR2(20),
    LASTNAME VARCHAR2(25),
    ADDRESS VARCHAR2(32),
    CITY VARCHAR2(20),
    STATE VARCHAR2(2),
    ZIP VARCHAR2(9)
);

CREATE TABLE CUSTOMER_SALE (
    SALES_ID NUMBER PRIMARY KEY,
    CUST_ID NUMBER,
    TOTAL_ITEM_AMOUNT NUMBER(10, 2),
    TAX_AMOUNT NUMBER(10, 2),
    TOTAL_SALE_AMOUNT NUMBER(10, 2),
    SALES_DATE DATE,
    SHIPPING_HANDLING_FEE NUMBER(5, 2),
    CONSTRAINT fk_sale_customer
        FOREIGN KEY (CUST_ID)
        REFERENCES CUSTOMER(CUST_ID)
);

CREATE TABLE SALES_ITEM (
    SALES_ID NUMBER,
    PRODUCT_ID NUMBER,
    SALE_AMOUNT NUMBER(10, 2),
    CONSTRAINT pk_sales_item
        PRIMARY KEY (SALES_ID, PRODUCT_ID),
    CONSTRAINT fk_salesitem_sale
        FOREIGN KEY (SALES_ID)
        REFERENCES CUSTOMER_SALE(SALES_ID),
    CONSTRAINT fk_salesitem_product
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID NUMBER,
    LOG_DATETIME DATE,
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE,
    CONSTRAINT pk_pet_log
        PRIMARY KEY (PRODUCT_ID, LOG_DATETIME),
    CONSTRAINT fk_petlog_product
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE OR REPLACE TRIGGER trg_petlog_bi
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.CREATED_BY_USER := USER;
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error inserting PET_CARE_LOG: ' || SQLERRM);
END;

CREATE OR REPLACE TRIGGER trg_petlog_bu
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF :OLD.CREATED_BY_USER != USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'You can only update your own log entries.');
    END IF;
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Error updating PET_CARE_LOG: ' || SQLERRM);
END;

CREATE OR REPLACE TRIGGER trg_petlog_bd
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20004, 'Only JOEMANAGER can delete log entries.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20005, 'Error deleting PET_CARE_LOG: ' || SQLERRM);
END;
